# ----
# Site

title: api.collectionlog.net
description: API documentation for collectionlog.net.
url: https://evansloan.github.com
google_analytics_key:
permalink: pretty
baseurl:

# -----
# Build

timezone: Etc/UTC

collections:
  documentation:
    title: Documentation
    position_number: 1
  collectionlog:
    title: Collection log
    position_number: 2
  hiscores:
    title: Hiscores
    position_number: 3
  items:
    title: Items
    position_number: 4

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "documentation"
    values:
      _hide_content: true
  -
    scope:
      type: "_collectionlog"
    values:
      _hide_content: true
  -
    scope:
      type: "_hiscores"
    values:
      _hide_content: true
  -
    scope:
      type: "_items"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
