version: '3.9'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      network: 'host'
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/local/collection-log-api
      - /usr/local/collection-log-api/node_modules

  db:
    container_name: postgres
    image: postgres
    ports:
      - '${DB_MAPPED_PORT:-5433}:${DB_PORT:-5432}'
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

volumes:
  pg: