openapi: "3.0.0"
info:
  version: "1.0"
  title: Collection log API
servers:
  - url: https://api.collectionlog.net
paths:
  /collectionlog/user/{username}:
    get:
      summary: Get collection log by username
      operationId: getCollectionLogByUsername
      tags:
        - collection
        - log
        - username
      parameters:
        - name: username
          in: path
          description: Username of collection log owner
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A JSON representation of a collection log
        "404":
          description: A collection log with the provided username was not found
