openapi: "3.0.0"
info:
  title: Collection log API
  version: 1.0
paths:
  /collectionlog/user/{username}:
    get:
      operationId: getCollectionLogByUsername
      summary: Get a specific collection log by username
      responses:
        '200':
          description: |-
            Successful collection log request