service: collection-log-api
app: collection-log-api
frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'local'}
  region: us-east-1
  logRetentionInDays: 14
  timeout: 29

  environment:
    SERVICE_NAME: ${self:service}
    STAGE_NAME: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

    DB_DIALECT: postgres
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}

  vpc:
    securityGroupIds:
      - !Ref LambdaSecurityGroup
    subnetIds:
      - !Ref PrivateSubnetA
      - !Ref PrivateSubnetB

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
            - ec2:AssignPrivateIpAddresses
            - ec2:UnassignPrivateIpAddresses
            - lambda:InvokeAsync
            - lambda:InvokeFunction
          Resource: '*'

functions:
  # Collection log endpoints
  create-collection-log:
    handler: src/handlers/collectionlog/create-collection-log.handler
    events:
      - httpApi:
          path: /collectionlog
          method: post

  get-collection-log-by-username:
    handler: src/handlers/collectionlog/get-collection-log-by-username.handler
    events:
      - httpApi:
          path: /collectionlog/user/{username}
          method: get

  update-collection-log:
    handler: src/handlers/collectionlog/update-collection-log.handler
    memorySize: 2048
    events:
      - httpApi:
          path: /collectionlog/{accountHash}
          method: put

  get-collection-log-exists:
    handler: src/handlers/collectionlog/get-collection-log-exists.handler
    events:
      - httpApi:
          path: /collectionlog/exists/{accountHash}
          method: get
  
  update-collection-log-details:
    handler: src/handlers/collectionlog/update-collection-log-details.handler
    timeout: 120

  delete-collection-log:
    handler: src/handlers/collectionlog/delete-collection-log.handler
    events:
      - httpApi:
          path: /collectionlog/delete
          method: delete

  # User endpoints
  create-user:
    handler: src/handlers/user/create-user.handler
    events:
      - httpApi:
          path: /user
          method: post

  get-user-typeahead:
    handler: src/handlers/user/get-user-typeahead.handler
    events:
      - httpApi:
          path: /user/typeahead/{username}
          method: get

  get-user-count:
    handler: src/handlers/user/get-user-count.handler
    events:
      - httpApi:
          path: /user/count
          method: get

  # Items endpoints
  get-items-recent:
    handler: src/handlers/items/get-recent.handler
    events:
      - httpApi:
          path: /items/recent/{username}
          method: get

  get-items-page-by-username:
    handler: src/handlers/items/get-page-by-username.handler
    events:
      - httpApi:
          path: /items/user/{username}
          method: get

  get-items-recent-global:
    handler: src/handlers/items/get-recent-global.handler
    events:
      - httpApi:
          path: /items/global
          method: get

  # Hiscores endpoints
  get-hiscores:
    handler: src/handlers/hiscores/get-hiscores.handler
    events:
      - httpApi:
          path: /hiscores/{page}
          method: get

  get-hiscores-rank-by-username:
    handler: src/handlers/hiscores/get-rank-by-username.handler
    events:
      - httpApi:
          path: /hiscores/rank/{username}
          method: get

  get-hiscores-ranks-by-username:
    handler: src/handlers/hiscores/get-account-type-ranks-by-username.handler
    events:
      - httpApi:
          path: /hiscores/ranks/{username}
          method: get

  # Scheduled tasks
  build-items-recent-global:
    handler: src/handlers/items/build-recent-global.handler
    timeout: 600
    events:
      - schedule: rate(10 minutes)

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-domain-manager
  - serverless-offline
 
custom:
  dev:
    domainName: dev.api.collectionlog.net

  prod:
    domainName: api.collectionlog.net

  customDomain:
    domainName: ${self:custom.${self:provider.stage}.domainName}
    certificateName: api.collectionlog.net
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    apiType: http
    endpointType: regional

resources:
  - ${file(resources/vpc.yml)}
  - ${file(resources/securitygroup.yml)}
  - ${file(resources/route.yml)}
  - ${file(resources/rds.yml)}
