### get-collection-log-by-username
GET {{HOST}}/collectionlog/user/{{USERNAME}}
Accept: application/json

### get-collection-log-exists
GET {{HOST}}/collectionlog/exists/{{ACCOUNT_HASH}}
Accept: application/json

### get-hiscores
GET {{HOST}}/hiscores/1
Accept: application/json

### get-account-type-ranks-by-username
GET {{HOST}}/hiscores/ranks/{{USERNAME}}
Accept: application/json

### get-page-by-username
GET {{HOST}}/items/user/{{USERNAME}}?pageName=Abyssal Sire
Accept: application/json

### get-recent
GET {{HOST}}/items/recent/{{USERNAME}}
Accept: application/json

### get-recent-global
GET {{HOST}}/items/global
Accept: application/json

### create-user
POST {{HOST}}/user
Content-Type: application/json

{
  "username": "_big hax",
  "account_hash": "14234242142"
}