Resources:
  CollectionLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CollectionLogTable-${self:provider.stage}
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: collectionlog_id
          AttributeType: S
      KeySchema:
        - AttributeName: collectionlog_id
          KeyType: HASH

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserTable-${self:provider.stage}
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH